services:
  - type: web
    name: rsvp
    runtime: docker
    rootDir: rsvpv2
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rsvp-db
          property: connectionString
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: rsvp-db
    plan: free
    databaseName: rsvp
    user: rsvp